- tests/checkbox/operate-checkbox.html
- tests/checkbox/read-checkbox-grouping.html
- tests/checkbox/read-checkbox.html
- tests/resources/TEMPLATE_TEST_FILE.html
- tests/resources/aria-at-harness.mjs
- tests/resources/at-commands.mjs
This test harness is a proof of concept, so the code is not final. In writing the harness I had to change the API from the previous tests in #12 .
Some questions:
You can look at this version of test harness here:
- [read-checkbox.html](https://spectranaut.github.io/aria-at/tests/checkbox/read-checkbox.html)
- [operate-checkbox.html](https://spectranaut.github.io/aria-at/tests/checkbox/operate-checkbox.html)
- [read-checkbox-grouping.html](https://spectranaut.github.io/aria-at/tests/checkbox/read-checkbox-grouping.html)
> Proof of concept test harness

- src/pages/results.js
We need a better long term solution
> Quick fix for result links

- scripts/test-reviewer.mjs
- tests/combobox-autocomplete-both/activate-switches-mode.html
- tests/combobox-autocomplete-both/navigate-switches-mode.html
- tests/resources/TEMPLATE_TEST_FILE.html
- tests/resources/aria-at-harness.mjs
The format of the `additional_output` list needed updating since the change in testing philosophy at the end of the prototype phase.
> Fix additional_output bug

- scripts/review-template.mustache
- tests/checkbox/navigate-through-checkbox-group-interaction.html
- tests/checkbox/navigate-through-checkbox-group.html
- tests/checkbox/navigate-to-checked-checkbox-interaction.html
- tests/checkbox/navigate-to-checked-checkbox.html
- tests/checkbox/navigate-to-unchecked-checkbox-interaction.html
- tests/checkbox/navigate-to-unchecked-checkbox.html
- tests/checkbox/operate-checkbox-interaction.html
- tests/checkbox/operate-checkbox.html
- tests/checkbox/read-checkbox-group-interaction.html
- tests/checkbox/read-checkbox-group.html
- tests/checkbox/read-checkbox-interaction.html
- tests/checkbox/read-checkbox.html
- tests/checkbox/read-checked-checkbox-interaction.html
- tests/checkbox/read-checked-checkbox.html
- tests/resources/at-commands.mjs
- tests/resources/keys.mjs
> Checkbox updates

- scripts/review-template.mustache
- scripts/test-reviewer.mjs
Implemented:
- radios instead of buttons for filter 
- link texts
- priorities "must have", "should have", "nice to have" instead of numbers
> Feedback on test plan review file

- scripts/review-template.mustache
- tests/checkbox/commands.json
- tests/checkbox/navigate-through-checkbox-group-interaction.html
- tests/checkbox/navigate-through-checkbox-group.html
- tests/checkbox/navigate-to-checked-checkbox-interaction.html
- tests/checkbox/navigate-to-checked-checkbox.html
- tests/checkbox/navigate-to-unchecked-checkbox-interaction.html
- tests/checkbox/navigate-to-unchecked-checkbox.html
- tests/checkbox/operate-checkbox-interaction.html
- tests/checkbox/operate-checkbox.html
- tests/checkbox/read-checkbox-group-interaction.html
- tests/checkbox/read-checkbox-group.html
- tests/checkbox/read-checkbox-interaction.html
- tests/checkbox/read-checkbox.html
- tests/checkbox/read-checked-checkbox-interaction.html
- tests/checkbox/read-checked-checkbox.html
- tests/resources/aria-at-harness.mjs
- tests/resources/at-commands.mjs
> Checkbox update 3

- tests/checkbox/commands.json
- tests/checkbox/navigate-into-checkbox-group-interaction.html
- tests/checkbox/navigate-into-checkbox-group.html
- tests/checkbox/navigate-out-of-checkbox-group-interaction.html
- tests/checkbox/navigate-out-of-checkbox-group.html
- tests/checkbox/read-checkbox-group-interaction.html
- tests/checkbox/read-checkbox-group.html
Address issues discovered in #52
> Checkbox update 4

- src/app.css
- src/components/configureRun.js
- src/components/runResults.js
1. Select all checkbox is hidden on the select tests page
2. Some formatting was off for the input file on the results page
3. The calculation of unexpected behaviors was off on the results page
> Fixing a few bugs in the runner

- README.md
Part of https://github.com/w3c/aria-at/issues/112
> Link to the CG page from the readme

- .github/ISSUE_TEMPLATE/test-plan.md
> Add an issue template for creating test plans

- tests/resources/aria-at-harness.mjs
> Avoid using <main> in tests

- src/pages/index.js
Also change headings to a list, part of #165
> Add intro text to the prototype

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/test-feedback.md
- .github/ISSUE_TEMPLATE/test-plan.md
Also clarify the existing template for creating new test plans.
Fixes #152.
> Add more issue templates

- README.md
I'm submitting this PR on behalf of @zcorpan, who has come up with a more thorough description of the project.
> Update readme with more explanation about the project

- tests/resources/aria-at-harness.mjs
- add `showSubmitButton` query string
- change button text to 'Submit Results' (and id to `submit-results`)
- add `postMessage` listener if test is loaded in iFrame, so that parent can trigger validation and review from outside. page listens for message with `data.type == 'submit'`
_Note: right now, `postMessage` messages are only respected if the parent window has the same origin as the iFrame. this restriction could be lifted if the tests are embedded in other 3rd-party apps._
> Update test harness to allow aria-at-app to trigger validation & review results

- scripts/create-tests.js
Should help to prevent errors similar to #230. Related to #267
> validate that a command actually exists for the combination of task, mode, and AT

- tests/menubar-editor/commands.json
- tests/menubar-editor/data/commands.csv
The jaws task name was incorrect
fixes #230
> Fix issue where menubar test 15 for jaws was not rendering

- tests/resources/aria-at-harness.mjs
> convert speech output textbox to textarea

- tests/resources/aria-at-harness.mjs
To test in ARIA-AT App:
1. Import the commit on this branch
```
yarn workspace server db-import-tests:dev -c 3570f1958ef45a4b47f77bc7808d5050db0c58e5
```
2. Update the run configuration to this commit: `3570f1958ef45a4b47f77bc7808d5050db0c58e5`. This also assumes that AT and browers are configured and your user is assigned to a test plan.
3. Open a test and verify that the text area is wider.
> Increase textarea width to 100%

- tests/resources/aria-at-harness.mjs
Replace select options for undesirable behavior with checkboxes.
> Replace select with checkbox

- .eslintrc.json
- .github/workflows/js-lint.yml
- package.json
- scripts/create-example-tests.js
- scripts/test-comparer.js
The dependency was already there, just plumbed it in and add a CI action to enforce it.
> chore: Setup ESLint Action and config

- .github/dependabot.yml
This adds Dependabot updates for non-security NPM updates and updates to GitHub Action dependencies
> chore: Add Dependabot config for NPM and Actions

- index.html
- review/checkbox.html
- review/combobox-autocomplete-both.html
- review/menubar-editor.html
- scripts/review-template.mustache
- scripts/test-reviewer.mjs
[Preview Tests](https://raw.githack.com/w3c/aria-at/review-button/index.html)
If you look at the "Preview Tests Link" and click any of the links that say "Review" for each test there is now a new button "Open Test # Page" which opens a popup with the example and the setup script run.
> Add button to open tests to review pages

- build/index.html
- build/review/alert.html
- build/review/breadcrumb.html
- build/review/checkbox-tri-state.html
- build/review/checkbox.html
- build/review/combobox-autocomplete-both-updated.html
- build/review/combobox-select-only.html
- build/review/command-button.html
- build/review/disclosure-faq.html
- build/review/disclosure-navigation.html
- build/review/horizontal-slider.html
- build/review/menu-button-actions-active-descendant.html
- build/review/menu-button-actions.html
- build/review/menubar-editor.html
- build/review/minimal-data-grid.html
- build/review/modal-dialog.html
- build/review/radiogroup-aria-activedescendant.html
- build/review/radiogroup-roving-tabindex.html
- build/review/rating-slider.html
- build/review/tabs-manual-activation.html
- build/review/toggle-button.html
- build/review/vertical-temperature-slider.html
- build/tests/resources/aria-at-test-io-format.mjs
- tests/resources/aria-at-test-io-format.mjs
[Preview Tests](https://raw.githack.com/w3c/aria-at/bocoup/fix-keys-input-from-collected-test/build/index.html)
Use keystrokes stored in collected test keypresses member.
> fix KeysInput.fromCollectedTest

- build/index.html
- build/review/alert.html
- build/review/breadcrumb.html
- build/review/checkbox-tri-state.html
- build/review/checkbox.html
- build/review/combobox-autocomplete-both-updated.html
- build/review/combobox-select-only.html
- build/review/command-button.html
- build/review/disclosure-faq.html
- build/review/disclosure-navigation.html
- build/review/horizontal-slider.html
- build/review/menu-button-actions-active-descendant.html
- build/review/menu-button-actions.html
- build/review/menubar-editor.html
- build/review/minimal-data-grid.html
- build/review/modal-dialog.html
- build/review/radiogroup-aria-activedescendant.html
- build/review/radiogroup-roving-tabindex.html
- build/review/rating-slider.html
- build/review/tabs-manual-activation.html
- build/review/toggle-button.html
- build/review/vertical-temperature-slider.html
- build/tests/resources/aria-at-test-io-format.mjs
- tests/resources/aria-at-test-io-format.mjs
[Preview Tests](https://raw.githack.com/w3c/aria-at/bocoup/fix-io-format-setup-script-description/build/index.html)
Default to empty string.
> fix io format setup script description

- build/index.html
- build/review/alert.html
- build/review/breadcrumb.html
- build/review/checkbox-tri-state.html
- build/review/checkbox.html
- build/review/combobox-autocomplete-both-updated.html
- build/review/combobox-select-only.html
- build/review/command-button.html
- build/review/disclosure-faq.html
- build/review/disclosure-navigation.html
- build/review/horizontal-slider.html
- build/review/menu-button-actions-active-descendant.html
- build/review/menu-button-actions.html
- build/review/menubar-editor.html
- build/review/minimal-data-grid.html
- build/review/modal-dialog.html
- build/review/radiogroup-aria-activedescendant.html
- build/review/radiogroup-roving-tabindex.html
- build/review/rating-slider.html
- build/review/tabs-manual-activation.html
- build/review/toggle-button.html
- build/review/vertical-temperature-slider.html
- build/tests/resources/aria-at-test-io-format.mjs
- build/tests/resources/aria-at-test-window.mjs
- tests/resources/aria-at-test-io-format.mjs
- tests/resources/aria-at-test-window.mjs
[Preview Tests](https://raw.githack.com/w3c/aria-at/increase-window-size/build/index.html)
Doubles the size of the test page window. No change was needed to make the window resizable since it is already resizable! Tested in Safari, Firefox and Chrome.
> Increase test page size

- build/index.html
- build/review/alert.html
- build/review/breadcrumb.html
- build/review/checkbox-tri-state.html
- build/review/checkbox.html
- build/review/combobox-autocomplete-both-updated.html
- build/review/combobox-select-only.html
- build/review/command-button.html
- build/review/disclosure-faq.html
- build/review/disclosure-navigation.html
- build/review/horizontal-slider.html
- build/review/menu-button-actions-active-descendant.html
- build/review/menu-button-actions.html
- build/review/menubar-editor.html
- build/review/minimal-data-grid.html
- build/review/modal-dialog.html
- build/review/radiogroup-aria-activedescendant.html
- build/review/radiogroup-roving-tabindex.html
- build/review/rating-slider.html
- build/review/tabs-manual-activation.html
- build/review/toggle-button.html
- build/review/vertical-temperature-slider.html
- metrics/coverage.md
[Preview Tests](https://raw.githack.com/w3c/aria-at/metric-updates/build/index.html)
- Add total number of test plans and tests across them all
- Fix number of total tests across all plans
- Add total number of assertions
- Add information relating to WAI-ARIA roles: total, number/percent tested, and list of linked items in appropriate section
- Add information relating to WAI-ARIA states/properties: total, number/percent tested, and list of linked items in appropriate section
- Fix number of WAI-ARIA roles
- Add information relating to APG examples: total, number/percent tested, and list of linked items in appropriate section
- Update number of tested APG patterns
- Add APG design pattern links
- Add project links to introductory section
> Metric Updates

- package-lock.json
- package.json
- scripts/update-reference.js
[Preview Tests](https://deploy-preview-592--aria-at.netlify.app)
Found that the NPM install was stalling from this dependency so swapped with simple-git https://www.npmjs.com/package/simple-git
Husky/lint-staged changes were because the hooks are currently broken, as there is no `npm test` script
> chore: migrate nodegit to simple-git

- .github/workflows/generate-and-commit-files.yml
- .github/workflows/js-lint.yml
- netlify.toml
- package-lock.json
- package.json
[Preview Tests](https://deploy-preview-649--aria-at.netlify.app)
Bump the packlock to v2 and Node 16 running now that the node-git block is resolved. Ran `npm audit fix` in separate commits after the original automated conversion
> chore: update package lock v2 and Node 16

- metrics/coverage.md
[Preview Tests](https://deploy-preview-676--aria-at.netlify.app)
Update the `collection of all current test plans` link to use the updated deploy url.
cc @richnoah
> Update broken link in coverage.md

- tests/command-button/reference/2022-4-8_124112/button.html
- tests/command-button/reference/2022-4-8_124112/button.setFocusAfterButton.html
- tests/command-button/reference/2022-4-8_124112/button.setFocusBeforeButton.html
- tests/command-button/reference/2022-4-8_124112/button.setFocusOnButton.html
- tests/link-span-text/reference/2022-4-6_14258/link.html
- tests/link-span-text/reference/2022-4-6_14258/link.setFocusAfterLink.html
- tests/link-span-text/reference/2022-4-6_14258/link.setFocusBeforeLink.html
- tests/link-span-text/reference/2022-4-6_14258/link.setFocusOnLink.html
- tests/toggle-button/reference/2022-4-8_135651/button.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusAfterButton.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusAfterButtonAndSetStateToPressed.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusBeforeButton.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusBeforeButtonAndSetStateToPressed.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusOnButton.html
- tests/toggle-button/reference/2022-4-8_135651/button.setFocusOnButtonAndSetStateToPressed.html
[Preview Tests](https://deploy-preview-709--aria-at.netlify.app)
> Fix navigation link positions in three test plans: link, command button and toggle button

- .eslintignore
- .eslintrc.json
- package-lock.json
- package.json
- scripts/test-reviewer.mjs
- tests/resources/aria-at-harness.mjs
- tests/resources/aria-at-test-io-format.mjs
- tests/resources/aria-at-test-run.mjs
- tests/resources/at-commands.mjs
- tests/resources/vrender.mjs
[Preview Tests](https://deploy-preview-671--aria-at.netlify.app)
Splitting out from other PR to see if this change only is OK with the build
> chore: add eslint-plugin-n

- scripts/review-index-template.mustache
- scripts/review-template.mustache
[Preview Tests](https://deploy-preview-674--aria-at.netlify.app)
- meta tag ouside of head
- P tag with inner lists that auto-close the tag
- add html lang value
- change radio to checked attribute
> fix: HTML validation of review template

- tests/checkbox-tri-state/data/commands.csv
[Preview Tests](https://deploy-preview-831--aria-at.netlify.app)
Updated NVDA and VoiceOver commands for several navigation tasks.
> Update NVDA and VoiceOver commands for checkbox (Mixed-State)

- tests/checkbox-tri-state/data/commands.csv
[Preview Tests](https://deploy-preview-842--aria-at.netlify.app)
Modify VoiceOver commands for task 7.
> Update VoiceOver commands for checkbox (Mixed-State)

- tests/disclosure-navigation/data/commands.csv
[Preview Tests](https://deploy-preview-845--aria-at.netlify.app)
Delete Up arrow command for VoiceOver when navigating backwards to a disclosure button for consistency.
> Update VoiceOver commands for Disclosure Navigation Menu

- tests/resources/aria-at-harness.mjs
[Preview Tests](https://deploy-preview-1007--aria-at.netlify.app)
Fix issue with `commands.json (v2)` failing to load when building v1 with clean build.
> Fix for `.collected.html` failing to render for v1

- scripts/v2makerUtil.js
[Preview Tests](https://deploy-preview-1004--aria-at.netlify.app)
> Correct bugs in the "v2" scripts

- tests/link-span-text/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1023--aria-at.netlify.app)
Specifies new VO quick nav settings for l and shift+l commands.
> Link: Specify new VO quick nav setting for l and shift+l

- tests/command-button/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1021--aria-at.netlify.app)
Specifies new VO settings for single quick key nav.
> Command Button: Revise VO settings for j and shift+j

- tests/toggle-button/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1022--aria-at.netlify.app)
Specifies the new VO setting for the j and shift+j commands.
> Toggle Button: Specify new VO quick nav setting for j and shift+j

- scripts/v2maker.js
[Preview Tests](https://deploy-preview-1026--aria-at.netlify.app)
> Use non-zero exit status to communicate errors

- types/aria-at-file.js
[Preview Tests](https://deploy-preview-1044--aria-at.netlify.app)
> Update documentation for types

- tests/command-button/data/voiceover_macos-commands.csv
- tests/toggle-button/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1048--aria-at.netlify.app)
Resolves #1030
- Update VoiceOver navigation commands for Command Button
- Update navigation VoiceOver commands for Toggle Button
> Update VoiceOver navigation commands for Command and Toggle Button

- tests/alert/data/assertions.csv
[Preview Tests](https://deploy-preview-1054--aria-at.netlify.app)
Resolve #1032 based on resolution in [April 18, 2024 meeting](https://www.w3.org/2024/04/18-aria-at-minutes.html#t02).
> Alert Test Plan: Change alert role assertion priority from "SHOULD to MAY

- tests/modal-dialog/data/jaws-commands.csv
- tests/modal-dialog/data/nvda-commands.csv
[Preview Tests](https://deploy-preview-1064--aria-at.netlify.app)
Solves #1063
> Update JAWS and NVDA Commands for Modal Dialog

- tests/modal-dialog/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1066--aria-at.netlify.app)
Resolves #1065
> Update VoiceOver Assertion for Modal Dialog

- tests/modal-dialog/data/jaws-commands.csv
- tests/modal-dialog/data/nvda-commands.csv
[Preview Tests](https://deploy-preview-1067--aria-at.netlify.app)
> Update JAWS and NVDA Assertions for Modal Dialog

- tests/horizontal-slider/data/voiceover_macos-commands.csv
[Preview Tests](https://deploy-preview-1082--aria-at.netlify.app)
> Update commands for Refactor Color Viewr Slider Test Plan

- tests/horizontal-slider/data/jaws-commands.csv
- tests/horizontal-slider/data/nvda-commands.csv
[Preview Tests](https://deploy-preview-1165--aria-at.netlify.app)
Resolves #1145
> Implement Feedback: Request Info Slider Test

- .github/workflows/generate-and-commit-files.yml
- lib/data/process-test-directory/utils.js
[Preview Tests](https://deploy-preview-1220--aria-at.netlify.app)
* Run `create-all-tests` in verbose by default so the error is properly reflected.
* Fix call to scoped `LOGGER` in `readCSVFile`.
> Run CI in verbose mode by default

- tests/accordion/data/jaws-commands.csv
[Preview Tests](https://deploy-preview-1263--aria-at.netlify.app)
Resolves #1260
> Update JAWS command for the Navigate into an accordion panel test

- tests/resources/aria-at-test-run.mjs
[Preview Tests](https://deploy-preview-1264--aria-at.netlify.app)
This patch is in service of https://github.com/w3c/aria-at-app/issues/1430
> Improve form UI for untestable assertions
