tests/resources/aria-at-harness.mjs

JS injection into examples was failing, which was causing check boxes to not receive focus when the test page was opened. This was happening in Chrome; I didn't check other browsers.
After debugging, I discovered that (at least in chrome) the new window first loads the `about:blank` page and then loads the proper URL. Therefore when we check the `readyState`, it was evaluated as `complete`, but the window was still pointed to `about:blank`.  So our code was being injected to the `about:blank` page, and was obviously failing.
This simply adds another check to ensure that the window's `origin` matches the same `origin` as the parent window before executing our script in the test page.

fix executeScriptInTestPage

---

tests/combobox-autocomplete-both/navigate-to-empty-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-empty-combobox.html
tests/combobox-autocomplete-both/navigate-to-filled-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-filled-combobox.html
tests/combobox-autocomplete-both/navigate-to-filled-open-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-filled-open-combobox.html
tests/combobox-autocomplete-both/read-empty-combobox-interaction.html
tests/combobox-autocomplete-both/read-empty-combobox.html
tests/combobox-autocomplete-both/read-filled-combobox-interaction.html
tests/combobox-autocomplete-both/read-filled-combobox.html
tests/combobox-autocomplete-both/read-filled-open-combobox-interaction.html
tests/combobox-autocomplete-both/read-filled-open-combobox.html
tests/resources/at-commands.mjs
tests/resources/keys.mjs

Some task to key commands were broken from typos, and the reading and interaction tests needed to be broken into separate files.

Fix combobox tests

---

tests/checkbox/navigate-through-checkbox-group-interaction.html
tests/checkbox/navigate-through-checkbox-group.html
tests/checkbox/navigate-to-checkbox-interaction.html
tests/checkbox/navigate-to-checkbox.html
tests/checkbox/navigate-to-checked-checkbox-interaction.html
tests/checkbox/navigate-to-checked-checkbox.html
tests/checkbox/operate-checkbox-interaction.html
tests/checkbox/operate-checkbox.html
tests/checkbox/read-checkbox-group-interaction.html
tests/checkbox/read-checkbox-group.html
tests/checkbox/read-checkbox-interaction.html
tests/checkbox/read-checkbox.html
tests/checkbox/read-checked-checkbox-interaction.html
tests/checkbox/read-checked-checkbox.html
tests/combobox-autocomplete-both/activate-switches-mode.html
tests/combobox-autocomplete-both/navigate-switches-mode.html
tests/combobox-autocomplete-both/navigate-to-empty-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-empty-combobox.html
tests/combobox-autocomplete-both/navigate-to-filled-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-filled-combobox.html
tests/combobox-autocomplete-both/navigate-to-filled-open-combobox-interaction.html
tests/combobox-autocomplete-both/navigate-to-filled-open-combobox.html
tests/combobox-autocomplete-both/navigate-to-popup.html
tests/combobox-autocomplete-both/read-empty-combobox-interaction.html
tests/combobox-autocomplete-both/read-empty-combobox.html
tests/combobox-autocomplete-both/read-filled-combobox-interaction.html
tests/combobox-autocomplete-both/read-filled-combobox.html
tests/combobox-autocomplete-both/read-filled-open-combobox-interaction.html
tests/combobox-autocomplete-both/read-filled-open-combobox.html

Hey @jongund -- I added an `applies_to`, like we discussed in the email. You could just edit your template and add a new row to include this information. For almost all the tests we write the value will be `["Desktop Screen Readers"]` unless the test only applies to a subset of screen readers, in which case it should list the screen readers it applies too, such as: `["NVDA", "JAWS"]`

Add 'applies_to' key to keep track of which AT the test tests

---

tests/support.json

Hey all,
The runner needs to know which ATs are supported and what to call them, and this should be kept in sync with the test suite. I'm suggesting adding this "support.json" file in the test directory that for now should be edited when there are new test plans or support for new ATs.
The file has two things:
1. an "ats" object that is a list of support ATs. Each supported AT has a human readable name and a key. The key is provided by a URL param in order to open the test to perform for a specific assistive technology.
2. an "examples" object. The examples object maps the directory names to a human readable name for the example. Eventually, we should have a programmatic way to get this information, but for now that is blocked on #133, at least.

Add support file

---

src/components/runResults.js
src/pages/results.js

Currently points to https://w3c.github.io/ as opposed to https://w3c.github.io/aria-at/.

Correct breadcrumb link to ARIA-AT Home page from the Results page

---

tests/support.json

Adding more information to this file that I think would be necessary in order to consume and run these tests by any third party! The extra information is the relationship between "applies_to" values in the tests.
What values can be put in the "applies_to" field was discussed in this issue: https://github.com/w3c/aria-at/issues/108
But I do have one question. We see in the tests an applies_to value of "VoiceOver". Is there a chance, @mcking65, that we should have a category call "VoiceOver" the refers to both "VoiceOver for MacOS" and "VoiceOver for iOS" -- or should those tests be update to revert to just "VoiceOver for MacOS"? These are "Test 2" and "Test 4" in the [combobox test plan](https://w3c.github.io/aria-at/review/combobox-autocomplete-both.html).

Update support file with 'applies_to' information

---

tests/resources/aria-at-harness.mjs

Set the default to JAWS even if `at` is not defined in the URL

---

tests/resources/aria-at-harness.mjs

This PR adds two features necessary to support bocoup/aria-at-app#103 (Editing test results and saving partial form values):
- ability to prevent the test harness from replacing the test contents html with the results table html, with a new `showResults` query string parameter (default value is `true` to maintain current behavior)
- `postMessage` communication to send two messages to any parent window of the test: a `loaded` message and a `results` message (this allows the parent app which embeds the test as an iFrame to cleanly know when async test loading has finished and when results have been submitted)
Note: the `postMessage` communication is sent to parent windows of any origin in order to support any app that may embed aria-at tests. This is safe as long as the test results do not …

Test Harness: add showResults query string and postMessage communication

---

tests/checkbox/index.html
tests/resources/aria-at-harness.mjs

This PR makes some important clarifications of language on test pages created by the harness. It also hacks elimination of mentions of mode for VoiceOver on macOS, which should get us by until we tackle issue #194.
Here's a summary of important changes:
1. Changes the intro paragraph to simplify wording and eliminate mention of mode for VoiceOver for Mac. Mode is now mentioned first in a prepositional phrase when applicable:
* Old format: How does VoiceOver for macOS respond after task "Navigate to the first checkbox. Note: it should be in the unchecked state." is performed in interaction mode?
* New format: Describe how VoiceOver for macOS behaves when performing task "Navigate to the first checkbox. Note: it should be in the unchecked state."
* New format: With JAWS in interaction mode, …

Cleanup harness text and labels

---

tests/resources/aria-at-harness.mjs

Modifies instructions on each test page to include a step for restoring default configuration. Points to a wiki help page. Just a sort of hack to get us by for now.
Also makes one small grammar adjustment related to the setup scription description.

Harness: Add screen reader config instruction

---

scripts/create-tests.js

fixes #193
Notes
* Bumps limit from 5 to 30
* Looks for columns in the csv named `assertion{x}`
* If an assertion is not found in the csv, it is not processed (for example, `assertion15` was not found)
* The assertions are already the last columns in the csv, so this shouldn't be an issue.

Bump the limit of test assertions to 30

---

.github/workflows/update-pr.yml
.pr-preview.json
index.html
scripts/review-index-template.mustache
scripts/test-reviewer.mjs

[Preview Tests](https://raw.githack.com/w3c/aria-at/pr-previewer-fixes/index.html)
The installed pr-previewer had two bugs:
1. The preview wasn't automatically attached to diffs unless they changed the number of tests.
2. Links to other pages from the review index got an access denied error.
I tried a couple of approaches to fixing including [reaching out to pr-previwer](https://github.com/tobie/pr-preview/issues/83) to find a solution before ultimately deciding to use a different solution and uninstall pr-previewer.
I switched to using a GitHub action called [pr-updater](https://github.com/tzkhan/pr-update-action) that adds templated branch name information to the title and body of all prs. 
The "Preview Tests" link above was automatically added in via the action. It uses the service …

Switch from pr-previwer to github action preview link

---

index.html
review/checkbox.html
review/combobox-autocomplete-both.html
review/menubar-editor.html
tests/checkbox/data/references.csv
tests/combobox-autocomplete-both/data/references.csv
tests/menubar-editor/data/references.csv

[Preview Tests](https://raw.githack.com/w3c/aria-at/aria-practice-link-reference-csv/index.html)

Add aria practice guide links to reference.csv(s)

---

index.html
review/checkbox.html
review/combobox-autocomplete-both.html
review/menubar-editor.html
tests/resources/aria-at-harness.mjs

[Preview Tests](https://raw.githack.com/w3c/aria-at/fix-undesirable-validation/index.html)
[Example test](https://raw.githack.com/w3c/aria-at/fix-undesirable-validation/tests/checkbox/test-04-navigate-to-checked-checkbox-reading.html?at=jaws)
To test validation:
1. Select "yes there are undesirable behaviors" for any command for any tests
2. Click the "submit results" button at the bottom of the page
3. You should see "required" by the "undesirable results" fieldset legend for the command in step (1)
4. Select "other"
2. Click the "submit results" button at the bottom of the page
3. You should see "required" by the "undesirable results" for the "other" input for the command
To test tab stop changes:
1. Select "yes there are undesirable changes"
2. Tab into the undesirable checkbox list
3. …

UX changes for undesirable behaviors and remove top level "All assertions are met" radio option

---

index.html
review/checkbox-tri-state.html
review/checkbox.html
review/combobox-autocomplete-both.html
review/combobox-select-only.html
review/menu-button-actions-active-descendant.html
review/menubar-editor.html
review/modal-dialog.html
review/tabs-manual-activation.html
tests/resources/at-commands.mjs

[Preview Tests](https://raw.githack.com/w3c/aria-at/command-sequences/index.html)
Fixes #363
---
This change supports the syntax proposed in https://github.com/w3c/aria-at/issues/363#issuecomment-789842774 
```
1,navigate forwards to grid,reading,JAWS,"T,DOWN","DOWN,DOWN",,,,
```
without changing the structure of `commands.json` (the strings can contain commas), and without changing the `CommandsAPI` used by `aria-at-harness.mjs`. This is to not shake the foundation for e.g. #434, while still giving test authors the option to use command sequences.
For example, given this in `test-01-navigate-to-unchecked-checkbox-reading.html`:
```
"nvda": [
[ "X_AND_SHIFT_X,X_AND_SHIFT_X" ],
[ "F_AND_SHIFT_F" ],
[ "TAB_AND_SHIFT_TAB" ],
[ "UP_AND_DOWN" ]
]
```
the rendered test instructions are:
> 4. …

Support command sequences in at-commands.mjs

---

build/index.html
build/review/checkbox-tri-state.html
build/review/checkbox.html
build/review/combobox-autocomplete-both-updated.html
build/review/combobox-select-only.html
build/review/command-button.html
build/review/disclosure-faq.html
build/review/disclosure-navigation.html
build/review/menu-button-actions-active-descendant.html
build/review/menu-button-actions.html
build/review/menubar-editor.html
build/review/minimal-data-grid.html
build/review/modal-dialog.html
build/review/radiogroup-aria-activedescendant.html
build/review/radiogroup-roving-tabindex.html
build/review/tabs-manual-activation.html
build/review/toggle-button.html
build/tests/resources/aria-at-harness.mjs
build/tests/resources/aria-at-test-run.mjs
build/tests/resources/vrender.mjs
scripts/create-example-tests.js
tests/resources/aria-at-harness.mjs
tests/resources/aria-at-test-run.mjs
tests/resources/vrender.mjs

[Preview Tests](https://raw.githack.com/w3c/aria-at/mzgoddard-harness-controller-and-render/build/index.html)
The harness module is given a test json of commands to perform and assertions to record the results of. This change replaces the manual DOM rendering and manual updates of the test instructions and result form with an object representing the test results, from which a second object, the instruction document, is created representing the structure, text, and user event handlers to update the first object. This separates the application state of the instructions and result entry from the DOM so that it can be reused outside the harness module.
This change further uses the added instruction document type and produces the existing DOM with a small virtual dom module. From the …

Replace harness instruction page rendering

---

build/index.html
build/review/checkbox-tri-state.html
build/review/checkbox.html
build/review/combobox-autocomplete-both-updated.html
build/review/combobox-select-only.html
build/review/command-button.html
build/review/disclosure-faq.html
build/review/disclosure-navigation.html
build/review/menu-button-actions-active-descendant.html
build/review/menu-button-actions.html
build/review/menubar-editor.html
build/review/minimal-data-grid.html
build/review/modal-dialog.html
build/review/radiogroup-aria-activedescendant.html
build/review/radiogroup-roving-tabindex.html
build/review/tabs-manual-activation.html
build/review/toggle-button.html
build/tests/resources/aria-at-harness.mjs
build/tests/resources/aria-at-test-io-format.mjs
build/tests/resources/aria-at-test-run.mjs
build/tests/resources/aria-at-test-window.mjs
build/tests/resources/at-commands.mjs
scripts/create-example-tests.js
tests/resources/aria-at-harness.mjs
tests/resources/aria-at-test-io-format.mjs
tests/resources/aria-at-test-run.mjs
tests/resources/aria-at-test-window.mjs
tests/resources/at-commands.mjs

[Preview Tests](https://raw.githack.com/w3c/aria-at/mzgoddard-harness-io-formatting/build/index.html)
- Add `TestRunInputOutput` class to gather various test information in a test html file.
- Move classes out of `aria-at-harness` so they can be used by dependents of `aria-at`.
The main change in this PR adds the `TestRunInputOutput` class. It takes `Input` helpers instances to produce the state for a `TestRun` instance and options for a `TestWindow` instance. Each `Input` type has a public interface representing some current information processed currently at runtime.
This PR includes static methods on those inputs that process currently available information in the test html files for that public interface. This design is intended to provide a means to iterate the input data format for …

Add harness input/output 

---

build/index.html
build/review/checkbox-tri-state.html
build/review/checkbox.html
build/review/combobox-autocomplete-both-updated.html
build/review/combobox-select-only.html
build/review/command-button.html
build/review/disclosure-faq.html
build/review/disclosure-navigation.html
build/review/menu-button-actions-active-descendant.html
build/review/menu-button-actions.html
build/review/menubar-editor.html
build/review/minimal-data-grid.html
build/review/modal-dialog.html
build/review/radiogroup-aria-activedescendant.html
build/review/radiogroup-roving-tabindex.html
build/review/tabs-manual-activation.html
build/review/toggle-button.html
build/tests/resources/aria-at-harness.mjs
build/tests/resources/aria-at-test-io-format.mjs
build/tests/resources/aria-at-test-run.mjs
tests/resources/aria-at-harness.mjs
tests/resources/aria-at-test-io-format.mjs
tests/resources/aria-at-test-run.mjs
tests/resources/types/aria-at-test-result.js
tests/resources/types/aria-at-test-run.js

[Preview Tests](https://raw.githack.com/w3c/aria-at/mzgoddard-test-result-json/build/index.html)
Export and import a json format of a test result without a test's verbose instruction information. This format is intended to make integration with aria-at-app easier.
This change includes:
- Improve JSDoc compatible typedef for AriaATTestRun.State (was TestRunState) in `tests/resources/types/aria-at-test-run.js` following typedefs/namespaces in `types`.
- Add JSDoc namespace `AriaATTestResult` in `tests/resources/types/aria-at-test-result.js` containing `AriaATTestResult.JSON` the import and export ttype for the new TestRunInputOutput methods.
- Forward errors from instruction document to test page document.
- Add `resultFormat` and `resultJSON` ConfigInput methods, that aria-at-harness sets …

Export TestResult json with TestRunInputOutput

---

build/index.html
build/review/checkbox-tri-state.html
build/review/checkbox.html
build/review/combobox-autocomplete-both-updated.html
build/review/combobox-select-only.html
build/review/command-button.html
build/review/disclosure-faq.html
build/review/disclosure-navigation.html
build/review/menu-button-actions-active-descendant.html
build/review/menu-button-actions.html
build/review/menubar-editor.html
build/review/minimal-data-grid.html
build/review/modal-dialog.html
build/review/radiogroup-aria-activedescendant.html
build/review/radiogroup-roving-tabindex.html
build/review/tabs-manual-activation.html
build/review/toggle-button.html
scripts/create-example-tests.js

[Preview Tests](https://raw.githack.com/w3c/aria-at/bocoup/encode-collected-files/build/index.html)
Node 14 `fs.writeFile` and `fs.writeFileSync` stop string casting objects passed as the content. To work with Node 14 and later, encode strings produced for collected test files ahead of time.

encode collected test files into uint8arrays

---

lib/data/command-tuples-at-mode-task-lookup.js
lib/data/parse-command-csv-row.js
scripts/create-example-tests.js
types/aria-at-file.js
types/aria-at-parsed.js
types/aria-at-validated.js

[Preview Tests](https://raw.githack.com/w3c/aria-at/bocoup/comma-separated-command-sequences/build/index.html)
- types:
- Add `keypresses` member to `AriaATParsed.Command`, `AriaATValidated.Command` and `AriaATFile.CollectedTest` types
- Clarify in `AriaATFile.CollectedTest` that `keystroke` members are human readable
- Rename command tuple nesting types in `AriaATFile` to reflect that they are deeper and deeper maps around `AriaATFile.CommandExtraInstructionTuple`
- `create-example-tests.js`:
- Replace `createATCommandFile` with `createCommandTuplesATModeTaskLookup`
- call `emitFile` with the output of `createCommandTuplesATModeTaskLookup`
- `lib/data`: Extract command csv row and tuple lookup functions from `create-example-tests.js` into relevant independent files

Support comma separated key sequences in test generation

---

.github/workflows/generate-and-commit-files.yml

Prevents Dependabot from keeping PR updated for newer dependency release

chore: Don't generate for Dependabot

---

.github/workflows/generate-and-commit-files.yml

Seems like it's still running on the Dependabot PRs, although not pushing anymore. Trying this to see if it will properly skip the job entirely.

chore: quote Dependabot branch filter

---

.github/workflows/generate-and-commit-files.yml
.github/workflows/js-lint.yml

Attempt 3 ...
Run the build like it currently since the skip isn't working, but don't push the result. This will at least test if the generate script works with any package changes.
Move the skiping to the lint job to avoid running it on push and PR, but try doublequotes for the globs

chore: build but don't push for Dependabot

---

.github/workflows/update-pr.yml

needed since it requires the GH token to update the issue/PR through the API

ci: use pull_request_target for PR preview

---

scripts/create-example-tests.js

[Preview Tests](https://deploy-preview-655--aria-at.netlify.app)
When the build script is run in Windows, strings which describe paths will use the reverse solidus character to separate directory names and file names. This character takes on special meaning within JavaScript string literals (it begins an escape sequence), so it must be transformed if it is to retain its intended purpose in that context.
Use `JSON.stringify` to properly sanitize a value which is inserted into JavaScript program code.
---
The particulars of this bug (i.e. the differences between operating systems) may make the problem seem rare, but sanitization is a concern for any code generation (and even for projects that target a single platform). I haven't seen any other instances of unsafe code generation, but we …

Correct generated code

---

package-lock.json
package.json

[Preview Tests](https://deploy-preview-666--aria-at.netlify.app)
Remove `htmlparser2` dependency as it's no longer being used.
Related to https://github.com/w3c/aria-at/pull/656#issuecomment-1076509042.

Remove `htmlparser2` dependency

---

tests/radiogroup-aria-activedescendant/data/commands.csv
tests/radiogroup-aria-activedescendant/data/js/setFocusOnFirstRadioButton.js
tests/radiogroup-aria-activedescendant/reference/2022-4-7_113015/radio-activedescendant.setFocusOnFirstRadioButton.html

[Preview Tests](https://deploy-preview-710--aria-at.netlify.app)
The following commands have been removed, all in reading mode for NVDA:
* Navigate to the first unchecked radio button in a group: Down Arrow
* Navigate to the last unchecked radio button in a group: Up Arrow
* Navigate to the first checked radio button in a group: Down Arrow
* Navigate to the last checked radio button in a group: Up Arrow
* Read information about an unchecked radio button: Insert+Up Arrow
* Read information about a checked radio button: Insert+Up Arrow
* Navigate to the next unchecked radio button: Down Arrow
* Navigate to the previous unchecked radio button: Up Arrow
* Navigate to the next checked radio button: Down Arrow
* Navigate to the previous checked radio button: Up Arrow

Remove Up/Down Arrow NVDA commands from certain radiogroup tests

---

scripts/create-example-tests.js
tests/resources/aria-at-test-io-format.mjs
tests/resources/at-commands.mjs

[Preview Tests](https://deploy-preview-794--aria-at.netlify.app)
Updated JAWS test instructions regarding exiting Forms Mode based on https://github.com/w3c/aria-at/issues/731#issuecomment-1158078906 and https://github.com/w3c/aria-at/issues/731#issuecomment-1167912369.
The instructions will now read as:
> Verify the Virtual Cursor is active by pressing Alt+Delete. If it is not, exit Forms Mode to activate the Virtual Cursor by pressing Escape.
instead of:
> Verify the Virtual Cursor is active by pressing Alt+Delete. If it is not, turn on the Virtual Cursor by pressing Insert+Z.

Update JAWS Test Instructions

---

tests/breadcrumb/data/commands.csv

[Preview Tests](https://deploy-preview-803--aria-at.netlify.app)
added a missing "Down Arrow" command to the "Navigate forwards out of the Breadcrumb navigation landmark" task for JAWS.

Update JAWS commands for breadcrumb

---

.github/dependabot.yml

[Preview Tests](https://deploy-preview-889--aria-at.netlify.app)
This PR is meant to reduce the frequency of dependabot notifications to avoid _potentially_ daily notification "spam".

Update dependabot checks to "monthly" for npm packages

---

lib/util/file-record.js

[Preview Tests](https://deploy-preview-912--aria-at.netlify.app)
Fix #910 
When inserting directories, walk its entries and merge items into the record. When inserting files, replace buffer with new buffer.
-----
This is a change to FileRecord.insert that I think follows how the method currently works for the path parameter to the record parameter. Before this change inserting a directory or file record would append it to the parent directory stated by the path parameter. That causes some odd outcomes when adding items that are already in the record.
Seeing #910 I think this is a reasonable change to make FileRecord work how I think others would anticipate. An alternative we could do would be to make FileRecord more strict and instead of merging and replacing records, error if there is a …

FileRecord.insert: merge directories and replace files

---

.gitattributes

[Preview Tests](https://deploy-preview-979--aria-at.netlify.app)
eslint/prettier are really arguing with git here...  everytime I run lint --fix, it modifies every file to replace CRLF - since the tooling does LF mode, we should tell git to treat the files as LF mode.

Force LF mode for js/mjs files.

---

lib/data/process-test-directory-v1.js
lib/data/process-test-directory.js
tests/resources/aria-at-harness.mjs
tests/resources/aria-at-test-io-format.mjs
tests/resources/aria-at-test-run.mjs
types/aria-at-file.js

[Preview Tests](https://deploy-preview-1003--aria-at.netlify.app)
see #969 
blocked from merging by #997 
This is an initial pass. These files are new to me so there is likely something I am missing (especially with output/serialization). I will leave this is as a draft for now and will have some side-channel conversations with others to ensure I am addressing everything.
Also, note that this is currently targeting `build-v2-test-format` to make viewing the diffs easier but this will target `main` once that branch is merged.

Update results collection form to support pass/fail assertion verdicts

---

tests/support.json

[Preview Tests](https://deploy-preview-1020--aria-at.netlify.app)
In a recent build of macOS, quick nav was split into two separate settings: one for single letter keys and one for arrow keys. Now the settings required for a test depends on whether the command sequence being tested is an arrow key command, quick nav letter command, or both.

support.json: Add VO settings for new single and arrow quick key nav added to VO in latest macOS

---

types/aria-at-file.js

[Preview Tests](https://deploy-preview-1025--aria-at.netlify.app)
This change was originally proposed and accepted in the aria-at-automation-harness repository (which maintains a copy of the type definition) [1].
[1] https://github.com/w3c/aria-at-automation-harness/pull/32#discussion_r1423307793

Update documentation of types per test format v2

---

lib/data/parse-test-csv-row.js
scripts/test-reviewer.mjs

[Preview Tests](https://deploy-preview-1035--aria-at.netlify.app)
Closes #1034.
* This PR removes an incorrect sort, which was based on older implementation details in `test-reviewer.mjs`.
* Explicitly sorts by `[tests.csv].presentationNumber` in `parse-test-csv-row.js`
This should make the order consistent between `<aria-at-url>/tests/<pattern>/index.html` and `<aria-at-url>/review/<pattern>.html`.

Explicitly sort by [tests.csv].presentationNumber on tests review page

---

lib/data/process-test-directory.js
scripts/test-reviewer.mjs
tests/resources/aria-at-test-io-format.mjs

[Preview Tests](https://deploy-preview-1038--aria-at.netlify.app)
Following the examples given for [assertionPhrase](https://github.com/w3c/aria-at/wiki/Test-Format-Definition-V2#assertionphrase), there is a need to also tokenize `assertionPhrase` in the same way `assertionStatement` is done.

Tokenize `assertionPhrase`

---

lib/data/parse-test-csv-row.js
lib/data/process-test-directory.js

[Preview Tests](https://deploy-preview-1042--aria-at.netlify.app)
See #1039.
This PR does the following:
* Update `tests.csv#assertions` column regex
* Supports 0 priority assertions when `tests.csv` is being parsed

Update tests.csv to override priority in assertions column

---

tests/resources/aria-at-test-io-format.mjs
tests/resources/types/aria-at-test-result.js

[Preview Tests](https://deploy-preview-1056--aria-at.netlify.app)
In reviewing https://github.com/w3c/aria-at-app/pull/1064, realized some harness support for these files were added to aria-at-app but not here.

Additional support for `MAY` in `aria-at-test-io-format.mjs`

---

scripts/update-reference.js

[Preview Tests](https://deploy-preview-1076--aria-at.netlify.app)
Addresses #1073.
This PR updates the `npm run update-reference` script to support the migration for example links in references.csv now that `w3.org/WAI/ARIA/apg` is being used in place of `w3c.github.io/aria-practices`.

Update `update-reference.js` script to support APG site migration

---

package-lock.json
package.json

[Preview Tests](https://deploy-preview-1086--aria-at.netlify.app)
While running the `yarn db-import-tests:dev` step in the local database setup instructions from a fresh clone, I was getting the following error.
```shellsession
commands.json for v2 test format may not exist
Error found: Error: ENOENT: no such file or directory, scandir '/Users/outofambit/src/meta-aria/aria-at-app/server/scripts/import-tests/tmp/build/tests'
at Object.readdirSync (node:fs:1527:3)
at buildTestsAndCreateTestPlanVersions (/Users/outofambit/src/meta-aria/aria-at-app/server/scripts/import-tests/index.js:118:31)
at async importTestPlanVersions (/Users/outofambit/src/meta-aria/aria-at-app/server/scripts/import-tests/index.js:80:7)
at async /Users/outofambit/src/meta-aria/aria-at-app/node_modules/sequelize/lib/sequ …
```

use a fork of cross-var with more up-to-date deps

---

tests/resources/aria-at-harness.mjs
tests/resources/aria-at-test-io-format.mjs
tests/resources/aria-at-test-run.mjs
tests/resources/types/aria-at-test-result.js

[Preview Tests](https://deploy-preview-1090--aria-at.netlify.app)
This PR replaces the checkbox with "yes" & "no" radio buttons in the assertion verdict form fields. This is part of the work of addressing [aria-at-ap/#1045](https://github.com/w3c/aria-at-app/issues/1045). The related app change is [aria-at-app/#1161](https://github.com/w3c/aria-at-app/pull/1161).
Note that nested fieldset was used as it matched other UI in the form. In my testing, both screen and screenreader, this proved usable but I am open to other structures.
Now both `assertion.passed` and `assertion.result` are `Boolean | null`. The `result` can technically be a string because of the legacy `failedReason` which no current form uses. I did not remove the code associated with this. This is also why `result` has been …

Radio buttons for assertion verdicts

---

tests/menu-button-actions-active-descendant/data/jaws-commands.csv
tests/menu-button-actions-active-descendant/data/nvda-commands.csv

[Preview Tests](https://deploy-preview-1097--aria-at.netlify.app)
Consistent with the request in #1094, when requesting info about a menuitem inside of a menu with insert+up, changed assertions so that:
* Assertions for setsize and posinset are optional.
* Assertions for menu container name and menu container role are omitted.
Made equivalent changes for both JAWS and NVDA.
Does not change VoiceOver because request info commands vo-f3 and vo-f4 are not expected to have different verbosity levels.

Action Menubutton with Active Descendant: Remove some assertions for insert+up

---

lib/data/process-test-directory-v1.js
lib/data/process-test-directory.js
tests/menu-button-actions-active-descendant/data/assertions.csv
tests/menu-button-actions-active-descendant/data/tests.csv

[Preview Tests](https://deploy-preview-1108--aria-at.netlify.app)
An error message was being thrown when running `npm run build` which read:
```
Unwanted U+FEFF found for key ﻿testId at index 0 while processing CSV.
Unwanted U+FEFF found for key ﻿assertionId at index 0 while processing CSV.
```
Found this to be coming from `tests/menu-button-actions-active-descendant/data/tests.csv` and `tests/menu-button-actions-active-descendant/data/assertions.csv`. This PR updates the message to add more detail and to remove the invisible character from both files:
```
[tests/menu-button-actions-active-descendant]: Unwanted U+FEFF found for key ﻿testId at index 0 while processing tests.csv.
[tests/menu-button-actions-active-descendant]: Unwanted U+FEFF found for key ﻿assertionId at index 0 while …
```

Update error message on "Unwanted U+FEFF" found in *.csv files

---

tests/radiogroup-aria-activedescendant/data/assertions.csv
tests/radiogroup-aria-activedescendant/data/jaws-commands.csv
tests/radiogroup-aria-activedescendant/data/nvda-commands.csv

[Preview Tests](https://deploy-preview-1142--aria-at.netlify.app)
Resolves #1094, #1141.
Changes:
1. Priority of assertion to convey state 'unchecked' to 3 from 2 (issue #1141).
2. For the JAWS insert+up command in tests for requesting info about a radio, remove assertions for posinset, setsize, group name, and group role (#1094).
3. Add insert+up testing to NVDA for the tests of requesting info about a radio and make the assertions equivalent to JAWS. This command was missing from the NVDA commands.

Radio Group Example Using aria-activedescendant: Change unchecked assertion to optional and omit 4 assertions from insert+up command for JAWS and NVDA

---

__test__/__snapshots__/createReviewPages.test.js.snap
scripts/test-reviewer/createReviewPages.mjs
scripts/test-reviewer/generateReviewPages.mjs

[Preview Tests](https://deploy-preview-1166--aria-at.netlify.app)
This is to avoid unnecessary snapshot failures, such as in #1165
* Ignore `lastEdited` value when creating review pages in test
* Ignore `commit` and `commitDescription` values when creating review index page in test
Those values had to be derived from the source folder rather than the tests' mock data so no need to track

Ignore variable values when checking mocks with `npm test`

---

tests/radiogroup-aria-activedescendant/data/assertions.csv
tests/radiogroup-aria-activedescendant/data/references.csv

[Preview Tests](https://deploy-preview-1157--aria-at.netlify.app)

Update references for radiogroup-aria-activedescendant

---

tests/radiogroup-aria-activedescendant/data/jaws-commands.csv
tests/radiogroup-aria-activedescendant/data/js/checkFirstRadioButtonAndSetFocusBeforeRadioGroup.js
tests/radiogroup-aria-activedescendant/data/js/setFocusBeforeRadioGroup.js
tests/radiogroup-aria-activedescendant/data/js/setFocusOnFirstRadioButton.js
tests/radiogroup-aria-activedescendant/data/nvda-commands.csv
tests/radiogroup-aria-activedescendant/data/scripts.csv
tests/radiogroup-aria-activedescendant/data/voiceover_macos-commands.csv
tests/radiogroup-aria-activedescendant/reference/2022-4-7_113015/radio-activedescendant.checkFirstRadioButtonAndSetFocusBeforeRadioGroup.html
tests/radiogroup-aria-activedescendant/reference/2022-4-7_113015/radio-activedescendant.setFocusBeforeRadioGroup.html
tests/radiogroup-aria-activedescendant/reference/2022-4-7_113015/radio-activedescendant.setFocusOnFirstRadioButton.html
tests/radiogroup-roving-tabindex/data/assertions.csv
tests/radiogroup-roving-tabindex/data/jaws-commands.csv
tests/radiogroup-roving-tabindex/data/js/checkFirstRadioButtonAndSetFocusBeforeRadioGroup.js
tests/radiogroup-roving-tabindex/data/js/setFocusBeforeRadioGroup.js
tests/radiogroup-roving-tabindex/data/js/setFocusOnFirstRadioButton.js
tests/radiogroup-roving-tabindex/data/nvda-commands.csv
tests/radiogroup-roving-tabindex/data/scripts.csv
tests/radiogroup-roving-tabindex/data/voiceover_macos-commands.csv
tests/radiogroup-roving-tabindex/reference/2021-3-15_144141/radio.checkFirstRadioButtonAndSetFocusBeforeRadioGroup.html
tests/radiogroup-roving-tabindex/reference/2021-3-15_144141/radio.setFocusBeforeRadioGroup.html
tests/radiogroup-roving-tabindex/reference/2021-3-15_144141/radio.setFocusOnFirstRadioButton.html

[Preview Tests](https://deploy-preview-1179--aria-at.netlify.app)
Resolves #1176
This update modifies the `radiogroup-aria-activedescendant` and `radiogroup-roving-tabindex` test plans to ensure consistency across all three screen readers (NVDA, JAWS, and VoiceOver):
*  The group label, previously hidden by the setup scripts, is now consistently visible in the test examples. Setup script descriptions have been updated accordingly to reflect this change.
*  An extra up arrow key press has been added to NVDA's test steps when navigating out of a radio group.
*  Assertions related to the group label when the screen reader cursor enters the radio group have been removed to standardize testing across screen readers.
*  Up and down arrow key commands have been incorporated into NVDA's test for …

Radio Group Test Plans Update

---

__test__/__mocks__/tests/alert/data/jaws-commands.csv
__test__/__snapshots__/createAllTests.test.js.snap
__test__/__snapshots__/createReviewPages.test.js.snap
lib/data/parse-command-csv-row.js
tests/resources/aria-at-test-io-format.mjs
tests/resources/at-commands.mjs

[Preview Tests](https://deploy-preview-1197--aria-at.netlify.app)
This PR does the following:
* Correctly defaults the `flattenObject()` function's `parentKey` param to an empty string. Without this, it was causing incorrect string matching comparisons during the review pages renders. So comparisons against `"undefinedmodifierAliases.vo"` when `"modifierAliases.vo"` was expected, would happen. This also applied to `keyAliases`.
* Consolidation of `flattenObject()`, `findValuesByKeys()` and `findValueByKey()` functions.
This addresses a build issue discussed in #1193.

fix: handling of `commands.json` aliases

---

.github/dependabot.yml

[Preview Tests](https://deploy-preview-1218--aria-at.netlify.app)
Will create grouped updates from Dependabot for minor bumps, but leave the major updates as separate PRs

chore: group Dependabot minor updates

---

.github/workflows/ensure-build-directory-is-absent.yml

Missed formatting with newly introduced workflow file

Fix formatting in `ensure-build-directory-is-absent` workflow

---

tests/resources/aria-at-test-run.mjs

[Preview Tests](https://deploy-preview-1295--aria-at.netlify.app)
Address https://github.com/w3c/aria-at-app/issues/1487
Address https://github.com/w3c/aria-at/issues/1278#issuecomment-3183836860

Display proper error message when `untestable` is checked and no `SEVERE` impact negative side effects have been set
